-- Create courses table
CREATE TABLE public.courses (
    id integer generated by default as identity primary key,
    prefix text not null,
    number text not null,
    title text not null,
    unique(prefix, number)
);

CREATE INDEX courses_prefix_idx on public.courses (prefix);

-- Create instructors table
CREATE TABLE public.instructors (
    id integer generated by default as identity primary key,
    first_name text not null,
    last_name text not null,
    unique(first_name, last_name)
);

CREATE INDEX instructors_last_name_idx on public.instructors (last_name);

-- Create sections table
CREATE TABLE public.sections (
    id integer generated by default as identity primary key,
    section_number text not null,
    course_id integer not null references public.courses(id) on delete cascade,
    instructor_id integer not null references public.instructors(id) on delete cascade,
    grade_a integer not null default 0,
    grade_b integer not null default 0,
    grade_c integer not null default 0,
    grade_d integer not null default 0,
    grade_f integer not null default 0,
    grade_p integer not null default 0,
    grade_np integer not null default 0,
    grade_w integer not null default 0,
    grade_i integer not null default 0,
    total_enroll integer not null default 0,
    unique(course_id, section_number)
);

CREATE INDEX sections_course_id_idx on public.sections (course_id);
CREATE INDEX sections_instructor_id_idx on public.sections (instructor_id);

-- Optional: Enable Row Level Security (RLS) if you plan on accessing from the frontend
-- ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.instructors ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.sections ENABLE ROW LEVEL SECURITY;

-- Optional: Allow public read access (usually needed if querying from the frontend)
-- CREATE POLICY "Allow public read access to courses." ON public.courses FOR SELECT USING (true);
-- CREATE POLICY "Allow public read access to instructors." ON public.instructors FOR SELECT USING (true);
-- CREATE POLICY "Allow public read access to sections." ON public.sections FOR SELECT USING (true);
